# ビルドしたフロントエンドとバックエンドのプログラムを用いてDockerイメージのビルドとDocker Hubへのプッシュを行うためのDocker Compose ymlファイル
# ビルドターゲット：Raspberry Pi 4B (arm64v8)
# ビルドイメージにはバックエンドのビルド出力と、フロントエンドのビルド出力を含め、運用環境でcompose.pull.ymlを実行することでイメージをプルして利用する想定。

services:
  # Docker Hubに Raspberry Pi 4B 向けのイメージをプッシュする。
  push-image:
    image: whoatemyapplepie/kids-home-base:${BASE_IMAGE_ALPINE_VERSION}-go${GO_VERSION}-node${NODE_VERSION}
    depends_on:
      build-image:
        condition: service_completed_successfully
    user: builder
    command:
      - /bin/sh
      - -c
      - |
        # Docker Hubにプッシュする。
        echo "Pushing Docker image for kids-home-base to Docker Hub..."
        docker push whoatemyapplepie/kids-home-base:${BASE_IMAGE_ALPINE_VERSION}-go${GO_VERSION}-node${NODE_VERSION}
        echo "Docker image for kids-home-base pushed successfully."
