# 運用環境をターゲットとするフロントエンドとバックエンドのプログラムのビルドをそれぞれ行うためのDocker Compose ymlファイル
# ビルドターゲット：Raspberry Pi 4B (arm64v8)
# このymlファイルを用いてプログラムをビルドした後、compose.push.ymlによりイメージのビルドとプッシュを行う想定。

services:
  # バックエンドのビルド
  build-backend:
    image: whoatemyapplepie/kids-home-base-backend:${BASE_IMAGE_ALPINE_VERSION}-go${GO_VERSION}
    platform: linux/arm64
    build:
      context: ./dockerfile_go_builder
      args:
        BASE_IMAGE_ALPINE_VERSION: ${BASE_IMAGE_ALPINE_VERSION}
        GO_VERSION: ${GO_VERSION}
    user: builder
    volumes:
      - ../src/backend:/home/builder/app
    command:
      - /bin/sh
      - -c
      - |
        # ビルドターゲット（Raspberry Pi 4B）に対応したバックエンドのビルドを実行する。
        go mod download
        go mod verify
        mkdir -p /home/builder/app/bin
        GOOS=linux GOARCH=arm64 go build -o /home/builder/app/bin/kids-home-base-backend ./main.go

  # フロントエンドのビルド
  build-frontend:
    image: whoatemyapplepie/kids-home-base-frontend:${BASE_IMAGE_ALPINE_VERSION}-node${NODE_VERSION}
    platform: linux/arm64
    build:
      context: ./dockerfile_node_builder
      args:
        BASE_IMAGE_ALPINE_VERSION: ${BASE_IMAGE_ALPINE_VERSION}
        NODE_VERSION: ${NODE_VERSION}
        NPM_VERSION: ${NPM_VERSION}
    user: builder
    volumes:
      - ../src/frontend:/home/builder/app
    command:
      - /bin/sh
      - -c
      - |
        # フロントエンドのビルドを実行する。
        npm install
        npm run build
