# 運用環境（Raspberry Pi 4B）でDockerイメージをプルするためのDocker Compose ymlファイル
# Dockerイメージは、compose.build.ymlでビルドされたイメージをDocker Hubからプルする。

services:
  # Docker HubからDockerイメージをプルして、運用環境でコンテナを起動する。
  kids-home-base-runner:
    image: whoatemyapplepie/kids-home-base:${BASE_IMAGE_ALPINE_VERSION}-go${GO_VERSION}-node${NODE_VERSION}
    restart: always
    environment:
      BASE_IMAGE_ALPINE_VERSION: ${BASE_IMAGE_ALPINE_VERSION}
      GO_VERSION: ${GO_VERSION}
      NODE_VERSION: ${NODE_VERSION}
      INITIAL_PASSWORD_HASH: ${INITIAL_PASSWORD_HASH}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SALT: ${SALT}
      ADD_TEST_DATA: ${ADD_TEST_DATA}
    volumes:
      - ./app:/app
    ports:
      - "23000:23000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
