# 開発環境で、デバッグ実行するためのDocker Compose ymlファイル
# ビルドターゲット：x64

services:
  # バックエンドのビルド
  build-backend:
    image: whoatemyapplepie/kids-home-base-backend:latest
    build:
      context: ./dockerfile_go_builder
    user: builder
    volumes:
      - ../src/backend:/home/builder/app
    ports:
      - "21226:21226"
    environment:
      - INITIAL_PASSWORD_HASH=${INITIAL_PASSWORD_HASH}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SALT=${SALT}
      - ADD_TEST_DATA=${ADD_TEST_DATA}
    command:
      - /bin/sh
      - -c
      - |
        # ビルドターゲット（x64）に対応したバックエンドのビルド・実行を行う。
        go mod download
        go mod verify
        mkdir -p /home/builder/app/bin
        GOOS=linux GOARCH=amd64 go build -o /home/builder/app/bin/kids-home-base-backend ./main.go
        chmod +x /home/builder/app/bin/kids-home-base-backend
        /home/builder/app/bin/kids-home-base-backend

  # フロントエンドのデバッグ実行
  build-frontend:
    image: whoatemyapplepie/kids-home-base-frontend:latest
    build:
      context: ./dockerfile_node_builder
    user: builder
    volumes:
      - ../src/frontend:/home/builder/app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
    command:
      - /bin/sh
      - -c
      - |
        # フロントエンドをデバッグ実行する。
        npm install
        npm run dev

  # ビルド出力を用いてDockerイメージをビルドする。
  # Docker Hubにプッシュする。
