# 運用環境をターゲットとするフロントエンドとバックエンドのプログラムのビルドをそれぞれ行うためのDocker Compose ymlファイル
# ビルドターゲット：Raspberry Pi 4B (arm64v8)
# このymlファイルを用いてプログラムをビルドした後、compose.push.ymlによりイメージのビルドとプッシュを行う想定。

services:
  # バックエンドのビルド
  build-backend:
    platform: linux/arm64
    image: whoatemyapplepie/kids-home-base-backend:${BASE_IMAGE_ALPINE_VERSION}-go${GO_VERSION}
    build:
      context: ./dockerfile_go_builder
      args:
        BASE_IMAGE_ALPINE_VERSION: ${BASE_IMAGE_ALPINE_VERSION}
        GO_VERSION: ${GO_VERSION}
    user: builder
    volumes:
      - ../src/backend:/home/builder/app
    command:
      - /bin/sh
      - -c
      - |
        # ビルドターゲット（Raspberry Pi 4B）に対応したバックエンドのビルドを実行する。
        go mod download
        go mod verify
        mkdir -p /home/builder/app/bin
        CGO_ENABLED=1 go build -o /home/builder/app/bin/kids-home-base-backend ./main.go

  # フロントエンドのビルド
  build-frontend:
    image: whoatemyapplepie/kids-home-base-frontend:${BASE_IMAGE_ALPINE_VERSION}-node${NODE_VERSION}
    build:
      context: ./dockerfile_node_builder
      args:
        BASE_IMAGE_ALPINE_VERSION: ${BASE_IMAGE_ALPINE_VERSION}
        NODE_VERSION: ${NODE_VERSION}
        NPM_VERSION: ${NPM_VERSION}
    user: builder
    volumes:
      - ../src/frontend:/home/builder/app
    command:
      - /bin/sh
      - -c
      - |
        # フロントエンドのビルドを実行する。
        npm install
        npm run build

  # ビルド出力を用いてDockerイメージをビルドする。
  build-image:
    image: whoatemyapplepie/kids-home-base:${BASE_IMAGE_ALPINE_VERSION}-go${GO_VERSION}-node${NODE_VERSION}
    platform: linux/arm64
    depends_on:
      build-backend:
        condition: service_completed_successfully
      build-frontend:
        condition: service_completed_successfully
    build:
      context: ..
      dockerfile: docker_kids-home-base/dockerfile_runner/Dockerfile
      args:
        BASE_IMAGE_ALPINE_VERSION: ${BASE_IMAGE_ALPINE_VERSION}
        GO_VERSION: ${GO_VERSION}
        NODE_VERSION: ${NODE_VERSION}
        NPM_VERSION: ${NPM_VERSION}
    environment:
      - INITIAL_PASSWORD_HASH=${INITIAL_PASSWORD_HASH}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SALT=${SALT}
      - ADD_TEST_DATA=${ADD_TEST_DATA}
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
      - NEXT_PUBLIC_WEATHER_FORECAST_URL=${NEXT_PUBLIC_WEATHER_FORECAST_URL}
