@startuml erd
計画 ||--o{ 1日の計画
1日の計画 ||--o{ 計画要素
計画要素 ||--|| 日時
計画要素 ||--|| タスク
定期的な計画 ||--o{ 定期的な計画要素
定期的な計画要素 ||--|| スケジュール間隔
定期的な計画要素 ||--|| 時刻
定期的な計画要素 ||--|| 開始日
定期的な計画要素 ||--|| 終了日
定期的な計画要素 ||--|| タスク
パスワードのハッシュ値 ||--|{ 大人ユーザーID
ログ ||--o{ ログ要素
ログ要素 ||--|| 日時
ログ要素 ||--|| ログレベル
ログ要素 ||--|| ログメッセージ
ログ要素 ||--|| 大人ユーザーID

@enduml